/**
 * Python HTTP wrapper for vibe CLI.
 * Uploaded into each Daytona sandbox as /home/daytona/vibe-server.py
 *
 * This script runs INSIDE the sandbox (isolated environment), not in our Node.js process.
 * It wraps the vibe CLI as an HTTP/SSE endpoint so our SvelteKit API route can proxy to it.
 *
 * Endpoints:
 *   GET  /health       - returns {"status":"ok"}
 *   POST /chat/stream  - SSE stream of vibe CLI output
 */
export const VIBE_SERVER_SCRIPT = [
	'import asyncio',
	'import json',
	'import logging',
	'import os',
	'import signal',
	'import sys',
	'import time',
	'import uuid',
	'',
	'from starlette.applications import Starlette',
	'from starlette.requests import Request',
	'from starlette.responses import JSONResponse',
	'from starlette.routing import Route',
	'from sse_starlette.sse import EventSourceResponse',
	'',
	'logging.basicConfig(level=logging.INFO, format="[vibe-server] %(asctime)s %(levelname)s %(message)s")',
	'logger = logging.getLogger("vibe-server")',
	'',
	'running_procs = []',
	'',
	'',
	'async def health(request: Request) -> JSONResponse:',
	'    logger.info("health check request received")',
	'    return JSONResponse({"status": "ok"})',
	'',
	'',
	'async def chat_stream(request: Request) -> EventSourceResponse:',
	'    try:',
	'        body = await request.json()',
	'    except Exception as exc:',
	'        logger.exception("invalid JSON body: %s", exc)',
	'        return JSONResponse({"error": "invalid_json"}, status_code=400)',
	'',
	'    trace_id = body.get("traceId") or uuid.uuid4().hex[:8]',
	'    prompt = body.get("prompt", "")',
	'    cwd = body.get("cwd", "/home/daytona")',
	'    logger.info("trace=%s request received prompt_len=%s cwd=%s", trace_id, len(prompt), cwd)',
	'',
	'    cmd = ["vibe", "--prompt", prompt, "--output", "streaming"]',
	'',
	'    async def event_generator():',
	'        start = time.time()',
	'        line_count = 0',
	'        proc = await asyncio.create_subprocess_exec(',
	'            *cmd,',
	'            stdout=asyncio.subprocess.PIPE,',
	'            stderr=asyncio.subprocess.STDOUT,',
	'            cwd=cwd,',
	'            env={**os.environ},',
	'        )',
	'        logger.info("trace=%s process started pid=%s", trace_id, proc.pid)',
	'        running_procs.append(proc)',
	'        try:',
	'            async for line in proc.stdout:',
	'                decoded = line.decode("utf-8", errors="replace").rstrip("\\n")',
	'                if not decoded:',
	'                    continue',
	'                line_count += 1',
	'                if line_count <= 20:',
	'                    logger.info("trace=%s line[%s]=%s", trace_id, line_count, decoded[:240])',
	'                elif line_count == 21:',
	'                    logger.info("trace=%s additional output suppressed", trace_id)',
	'                payload = {"type": "chunk", "traceId": trace_id, "index": line_count, "content": decoded}',
	'                yield {"data": json.dumps(payload)}',
	'            await proc.wait()',
	'            elapsed_ms = int((time.time() - start) * 1000)',
	'            logger.info("trace=%s process finished exit=%s lines=%s elapsedMs=%s", trace_id, proc.returncode, line_count, elapsed_ms)',
	'            yield {"data": json.dumps({"type": "done", "traceId": trace_id, "exitCode": proc.returncode, "lineCount": line_count, "elapsedMs": elapsed_ms})}',
	'        except asyncio.CancelledError:',
	'            logger.warning("trace=%s stream cancelled, terminating pid=%s", trace_id, proc.pid)',
	'            proc.terminate()',
	'            await proc.wait()',
	'            raise',
	'        except Exception as exc:',
	'            logger.exception("trace=%s stream error: %s", trace_id, exc)',
	'            yield {"data": json.dumps({"type": "error", "traceId": trace_id, "message": str(exc)})}',
	'        finally:',
	'            if proc in running_procs:',
	'                running_procs.remove(proc)',
	'',
	'    return EventSourceResponse(event_generator())',
	'',
	'',
	'def handle_sigterm(*_):',
	'    logger.info("SIGTERM received, terminating %s running process(es)", len(running_procs))',
	'    for proc in running_procs:',
	'        try:',
	'            proc.terminate()',
	'        except ProcessLookupError:',
	'            pass',
	'    sys.exit(0)',
	'',
	'',
	'signal.signal(signal.SIGTERM, handle_sigterm)',
	'',
	'async def debug(request: Request) -> JSONResponse:',
	'    """Run diagnostics: vibe version, config, env, and quick API test."""',
	'    results = {}',
	'    try:',
	'        proc = await asyncio.create_subprocess_exec("vibe", "--version", stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT)',
	'        out, _ = await asyncio.wait_for(proc.communicate(), timeout=10)',
	'        results["vibe_version"] = out.decode().strip()',
	'    except Exception as e:',
	'        results["vibe_version_error"] = str(e)',
	'    try:',
	'        with open("/home/daytona/.vibe/config.toml") as f:',
	'            results["config"] = f.read()',
	'    except Exception as e:',
	'        results["config_error"] = str(e)',
	'    results["has_mistral_key"] = bool(os.environ.get("MISTRAL_API_KEY"))',
	'    results["mistral_key_prefix"] = (os.environ.get("MISTRAL_API_KEY") or "")[:8] + "..."',
	'    try:',
	'        proc = await asyncio.create_subprocess_exec("vibe", "--prompt", "say hello", "--output", "text", "--max-turns", "1", stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT)',
	'        out, _ = await asyncio.wait_for(proc.communicate(), timeout=30)',
	'        results["quick_test"] = out.decode()[:500]',
	'        results["quick_test_exit"] = proc.returncode',
	'    except asyncio.TimeoutError:',
	'        results["quick_test"] = "TIMEOUT after 30s"',
	'        try:',
	'            proc.kill()',
	'        except Exception:',
	'            pass',
	'    except Exception as e:',
	'        results["quick_test_error"] = str(e)',
	'    return JSONResponse(results)',
	'',
	'',
	'app = Starlette(',
	'    routes=[',
	'        Route("/health", health, methods=["GET"]),',
	'        Route("/chat/stream", chat_stream, methods=["POST"]),',
	'        Route("/debug", debug, methods=["GET"]),',
	'    ],',
	')',
	'',
	'if __name__ == "__main__":',
	'    import uvicorn',
	'    logger.info("starting vibe server on 0.0.0.0:3000")',
	'    uvicorn.run(app, host="0.0.0.0", port=3000, log_level="info")'
].join('\n');
